name: chaparapp
description: "A sample project for Chapar company"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  get_it: ^7.6.4
  dio: ^5.4.0
  auto_route: ^7.8.4
  equatable: ^2.0.5
  flutter_spinkit: ^5.2.0
  intl: any
  flutter_svg: ^2.0.9
  overlay_support: ^2.1.0
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.5
  auto_route_generator: 7.2.0
  json_serializable: ^6.7.1
  lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/applogo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/applogo.png"
    background_color: "#FFFFFF"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
flutter_intl:
  enabled: true
  class_name: S
  main_locale: fa
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/applogo.png
  fullscreen: true
  ios: true
  android: true
  web: true
